name: morphing
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  alice: ^0.2.3
  dio: ^4.0.0
  dartz: ^0.10.0-nullsafety.2
  dio_http_cache:
    git:
      url: https://github.com/mahidul-islam/dio-http-cache
      ref: master

  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2
  firebase_auth: ^2.0.0
  # cloud_firestore: ^2.3.0

  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  pedantic: ^1.11.1
  get_it: ^7.1.3
  shared_preferences: ^2.0.7
  flutter_svg: ^0.22.0

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+1
  image_cropper: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/json/
    - assets/image/
    - assets/image/ready/
    - assets/image/ready/sample/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
